FROM node as builder
MAINTAINER BrianVo vnbaotran@gmail.com

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

ARG TZ=UTC
ENV TZ ${TZ}

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN mkdir -p /srv/angular

WORKDIR /srv/angular

COPY . .

EXPOSE 8080 49152

WORKDIR /srv/angular/

RUN npm install

RUN npm run build

RUN chmod +x ./docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]

#CMD /bin/bash -c "envsubst '$PORT' < /etc/nginx/conf.d/default/default.conf > /etc/nginx/conf.d/default/default.conf" && nginx -g 'daemon off;'""
#CMD sed -i -e 's/$PORT'"$PORT"'/g' /etc/nginx/conf.d/default/default.conf && nginx -g 'daemon off;'
#/bin/bash -c "envsubst '$PORT' < /etc/nginx/conf.d/default/default.conf > /etc/nginx/conf.d/default/default.conf" && nginx -g 'daemon off;'