import { ICourse } from '../interfaces/ICourse';
import { CoursePrerequisite } from '../interfaces/CoursePrerequisites';
import { IProgram } from '../interfaces/IProgram';

export const DEFAULT_COURSES: ICourse[] = [
  {
    courseId: 'CSIS 1175',
    course_code: 'CSIS 1175',
    title: 'Introduction to Programming I',
    prerequisites: [],
    credit: 3,
  },
  {
    courseId: 'CSIS 1275',
    course_code: 'CSIS 1275',
    title: 'Introduction to Programming II',
    prerequisites: [],
    credit: 3,
  },
  {
    courseId: 'CSIS 2175',
    course_code: 'CSIS 2175',
    title: 'Adv Integrated Software Dev',
    prerequisites: [],
    credit: 3,
  },
  {
    courseId: 'CSIS 2200',
    course_code: 'CSIS 2200',
    title: 'Systems Analysis and Design',
    prerequisites: [],
    credit: 3,
  },
  {
    courseId: 'CSIS 2260',
    course_code: 'CSIS 2260',
    title: 'Operating Systems',
    prerequisites: [],
    credit: 3,
  },
  {
    courseId: 'CSIS 2270',
    course_code: 'CSIS 2270',
    title: 'Virtualization and Computer Networking',
    prerequisites: [],
    credit: 3,
  },
];

export const COURSE_PREREQUISITES: CoursePrerequisite[] = [
  {
    courseId: 'CSIS 1175',
    course_code: 'CSIS 1175',
    title: 'Introduction to Programming I',
    credit: 3,
    prerequisites: [],
  },
  {
    courseId: 'CSIS 1275',
    course_code: 'CSIS 1275',
    title: 'Introduction to Programming II',
    credit: 3,
    prerequisites: [],
  },
  {
    courseId: 'CSIS 2175',
    course_code: 'CSIS 2175',
    title: 'Adv Integrated Software Dev',
    credit: 3,
    prerequisites: [],
  },
  {
    courseId: 'CSIS 2200',
    course_code: 'CSIS 2200',
    title: 'Systems Analysis and Design',
    credit: 3,
    prerequisites: [],
  },
  {
    courseId: 'CSIS 2260',
    course_code: 'CSIS 2260',
    title: 'Operating Systems',
    credit: 3,
    prerequisites: [],
  },
  {
    courseId: 'CSIS 2270',
    course_code: 'CSIS 2270',
    title: 'Virtualization and Computer Networking',
    credit: 3,
    prerequisites: [],
  },
  // {
  //   courseId: 'CSIS 2300',
  //   course_code: 'CSIS 2300',
  //   title: 'Database I',
  //   credit: 3,
  //   prerequisites: [['CSIS 2200']],
  // },
  // {
  //   courseId: 'CSIS 3155',
  //   course_code: 'CSIS 3155',
  //   title: 'Computer Network Security',
  //   credit: 3,
  //   prerequisites: [['CSIS 2260'], ['CSIS 2270']],
  // },
  // {
  //   courseId: 'CSIS 3175',
  //   course_code: 'CSIS 3175',
  //   title: 'Mobile Application Development I',
  //   credit: 3,
  //   prerequisites: [['CSIS 1275'], ['CSIS 2175']],
  // },
  // {
  //   courseId: 'CSIS 3160',
  //   course_code: 'CSIS 3160',
  //   title: 'Evidence Imaging',
  //   credit: 3,
  //   prerequisites: [['CSIS 2260']],
  // },
  // {
  //   courseId: 'CSIS 3275',
  //   course_code: 'CSIS 3275',
  //   title: 'Software Engineering',
  //   credit: 3,
  //   prerequisites: [
  //     ['CSIS 2200', 'CSIS 1275'],
  //     ['CSIS 2200', 'CSIS 2175'],
  //   ],
  // },
  // {
  //   courseId: 'CSIS 3270',
  //   course_code: 'CSIS 3270',
  //   title: 'Advanced Networking',
  //   credit: 3,
  //   prerequisites: [['CSIS 2270']],
  // },
];

export const PROGRAM: IProgram = {
  first_year: [
    [
      {
        url: '/course/csis-1175',
        course_code: 'CSIS 1175',
        prerequisitesStr:
          'Pre-Calculus 11 (C or better) or Foundations of Math 11 (C or better) or MATU 0410 (C or better) or approved substitute OR currently active in:\nPDD Information and Communication Technology or\nPDD Data Analytics or\nPBD Computer and Information Systems',
        prerequisites: [['PDICT'], ['PDDATA'], ['PBDCIS']],
        title: 'Introduction to Programming I',
        credit: '3.00',
      },
      {
        url: '/course/cmpt-1110',
        course_code: 'CMPT 1110',
        prerequisitesStr:
          'MATH 1110 with a minimum grade of C; or BC Pre-Calculus 12 with a minimum grade of B; or CSIS 1110',
        prerequisites: [['CSIS 1110'], ['MATH 1110'], ['Pre-Calculus 12']],
        title: 'C++ Programming',
        credit: '3.00',
      },
    ],
    [
      {
        url: '/course/csis-1275',
        course_code: 'CSIS 1275',
        prerequisitesStr:
          'A grade of C or better in either CSIS 1175 or CMPT1110',
        prerequisites: [['CSIS 1175'], ['CMPT 1110']],
        title: 'Introduction to Programming II',
        credit: '3.00',
      },
      {
        url: '/course/csis-2175',
        course_code: 'CSIS 2175',
        prerequisitesStr:
          'Courses listed here must be completed prior to this course:\nA grade of C or better in CSIS 1175 \n',
        prerequisites: [['CSIS 1175']],
        title: 'Adv Integrated Software Dev',
        credit: '3.00',
      },
    ],
    {
      url: '/course/csis-2200',
      course_code: 'CSIS 2200',
      prerequisitesStr:
        '9 credits in any 1000-level Commerce and Business Administration courses OR currently active in:\nPDD Information and Communication Technology\nPDD Data Analytics\nPDD Accounting Studies\nPDD Accounting\nPBD Computer and Information Systems\nPBD Accounting\nPBD Accounting and Finance\nPDD Project Management\nPDD Supply Chain Management\nPBD International Supply Chain Management\nPBD Health Information Management',
      prerequisites: [
        ['PDICT'],
        ['PDDATA'],
        ['PDACCS'],
        ['PDACCT'],
        ['PBDCIS'],
        ['PBDACCT'],
        ['PBACCF'],
        ['PDPMGMT'],
        ['PDSCMGT'],
        ['PBDISCM'],
        ['PDHIM'],
      ],
      title: 'Systems Analysis and Design',
      credit: '3.00',
    },
    {
      url: '/course/csis-2260',
      course_code: 'CSIS 2260',
      prerequisitesStr:
        'Pre-Calculus 11 (C or better) or Foundations of Math 11 (C or better) or MATU 0410 (C or better) or approved substitute OR currently active in:\nPDD Emerging Technology\nPBD Computer and Information Systems',
      prerequisites: [
        ['PDICT'],
        ['PBDCIS'],
        ['Pre-Calculus 11'],
        ['MATU 0410'],
        ['Foundations of Math 11'],
      ],
      title: 'Operating Systems',
      credit: '3.00',
    },
    {
      url: '/course/csis-2270',
      course_code: 'CSIS 2270',
      prerequisitesStr:
        'Pre-Calculus 11 (C or better) or Foundations of Math 11 (C or better) or MATU 0410 (C or better) or approved substitute OR currently active in:\nPDD Emerging Technology\nPBD Computer and Information Systems',
      prerequisites: [['PBDCIS'], ['PDICT']],
      title: 'Virtualization and Computer Networking',
      credit: '3.00',
    },
    {
      url: '/course/csis-2300',
      course_code: 'CSIS 2300',
      prerequisitesStr: 'Min grade C in CSIS 2200 ',
      prerequisites: [['CSIS 2200']],
      title: 'Database I',
      credit: '3.00',
    },
    {
      url: '/course/csis-3155',
      course_code: 'CSIS 3155',
      prerequisitesStr: 'Min grade C in CSIS 2260 and CSIS 2270',
      prerequisites: [['CSIS 2260', 'CSIS 2270']],
      title: 'Computer Network Security',
      credit: '3.00',
    },
    {
      url: '/course/csis-3175',
      course_code: 'CSIS 3175',
      prerequisitesStr: 'Min C in (CSIS 1275 OR CSIS 2175) ',
      prerequisites: [['CSIS 1275'], ['CSIS 2175']],
      title: 'Mobile Application Development I',
      credit: '3.00',
    },
    {
      url: '/course/csis-3275',
      course_code: 'CSIS 3275',
      prerequisitesStr: 'Min grade C in CSIS 2200 and (CSIS 1275 OR CSIS 2175)',
      prerequisites: [['CSIS 2200'], ['CSIS 1275', 'CSIS 2175']],
      title: 'Software Engineering',
      credit: '3.00',
    },
    [
      {
        url: '/course/csis-1280',
        course_code: 'CSIS 1280',
        prerequisitesStr:
          'Pre-Calculus 11 (C or better) or Foundations of Math 11 (C or better) or MATU 0410 (C or better) or approved substitute OR currently active in:\nPDD Information and Communication Technology or\nPDD Data Analytics or\nPBD Computer and Information Systems',
        title: 'Multimedia Web Development',
        prerequisites: [['PBDCIS'], ['PDDATA'], ['PDICT']],
        credit: '3.00',
      },
      {
        url: '/course/csis-3160',
        course_code: 'CSIS 3160',
        prerequisitesStr: 'Min grade C in CSIS 2260',
        prerequisites: [['CSIS 2260']],
        title: 'Evidence Imaging',
        credit: '3.00',
      },
    ],
  ],
  second_year: {
    emmerge_tech: [
      [
        {
          url: '/course/csis-3540',
          course_code: 'CSIS 3540',
          prerequisitesStr:
            'A grade of C or better in the following courses: CSIS 2300 and (CSIS 1175 or CMPT 1110).',
          prerequisites: [
            ['CSIS 2300', 'CSIS 1175'],
            ['CSIS 2300', 'CMPT 1110'],
          ],
          title: 'Client Server Systems',
          credit: '3.00',
        },
        {
          url: '/course/csis-4050',
          course_code: 'CSIS 4050',
          prerequisitesStr:
            'Courses listed here must be completed prior to this course:\nA grade of C or better in (either CSIS 1275 or CSIS 2175) and CSIS 2300\n',
          prerequisites: [
            ['CSIS 1275', 'CSIS 2300'],
            ['CSIS 2175', 'CSIS 2300'],
          ],
          title: 'Advanced OO Prog for Bus App',
          credit: '3.00',
        },
      ],
      {
        url: '/course/csis-3270',
        course_code: 'CSIS 3270',
        prerequisitesStr: 'Min grade C in CSIS 2270',
        prerequisites: [['CSIS 2270']],
        title: 'Advanced Networking',
        credit: '3.00',
      },
      {
        url: '/course/csis-3280',
        course_code: 'CSIS 3280',
        prerequisitesStr: 'Min grade C in CSIS 1280',
        prerequisites: [['CSIS 1280']],
        title: 'Web Based Scripting',
        credit: '3.00',
      },
      {
        url: '/course/csis-3375',
        course_code: 'CSIS 3375',
        prerequisitesStr: 'Min grade C in CSIS 3175',
        prerequisites: [['CSIS 3175']],
        title: 'UX Design in Mobile Applications',
        credit: '3.00',
      },
      {
        url: '/course/csis-3380',
        course_code: 'CSIS 3380',
        prerequisitesStr: 'CSIS 1280 with grade C or better',
        prerequisites: [['CSIS 1280']],
        title: 'Advanced Web Programming with JavaScript\u00a0and AJAX',
        credit: '3.00',
      },
      {
        url: '/course/csis-3475',
        course_code: 'CSIS 3475',
        prerequisitesStr: 'Min C in (CSIS 1275 or CSIS 2175)',
        prerequisites: [['CSIS 1275', 'CSIS 2175']],
        title: 'Data Structures and Algorithms',
        credit: '3.00',
      },
      {
        url: '/course/csis-4175',
        course_code: 'CSIS 4175',
        prerequisitesStr: 'Min grade C in CSIS 3175',
        prerequisites: [['CSIS 3175']],
        title: 'Mobile Application Development II',
        credit: '3.00',
      },
      {
        url: '/course/csis-4270',
        course_code: 'CSIS 4270',
        prerequisitesStr: 'Min grade C in CSIS 3155',
        prerequisites: [['CSIS 3155']],
        title: 'Cloud Infrastructure',
        credit: '3.00',
      },
      {
        url: '/course/csis-4280',
        course_code: 'CSIS 4280',
        prerequisitesStr: 'Min grade C in CSIS 3175\n ',
        prerequisites: [['CSIS 3175']],
        title: 'Special Topics in Web/Mobile Application Development',
        credit: '3.00',
      },
      {
        url: '/course/csis-4495',
        course_code: 'CSIS 4495',
        prerequisitesStr:
          'A minimum C grade in the following courses:\nCSIS 2300 and CSIS 3275\nand (CSIS 4175 or 2 of (CSIS 3300, CSIS 3360, CSIS 3860)).\n \nIt is recommended that a student should have obtained 45 credits towards a CSIS credential such as the PBD-CIS before attempting this course.',
        prerequisites: [
          ['CSIS 2300', 'CSIS 3275', 'CSIS 4175'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3300', 'CSIS 3360'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3360', 'CSIS 3860'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3860', 'CSIS 3300'],
        ],
        title: 'Applied Research Project',
        credit: '3.00',
      },
    ],
    data_analysis: [
      [
        {
          url: '/course/csis-3190',
          course_code: 'CSIS 3190',
          prerequisitesStr:
            'min grade C in CSIS 1190 OR currently active in the \nPDD Data Analytics\nPBD Computer Information System Data Analytics',
          prerequisites: [['PDDATA'], ['PBDCIS']],
          title: 'Business Support Systems with Excel',
          credit: '3.00',
        },
        {
          url: '/course/csis-3290',
          course_code: 'CSIS 3290',
          prerequisitesStr:
            'min grade C in CSIS 1190 OR currently active in the \nPDD Data Analytics\nPBD Computer and Information Systems \n(Note: CSIS 1175 recommended)',
          prerequisites: [['PDDATA'], ['PBDCIS']],
          title: 'Fundamentals of Machine Learning in Data Science',
          credit: '3.00',
        },
      ],
      {
        url: '/course/busn-2429',
        course_code: 'BUSN 2429',
        prerequisitesStr:
          'FINC 1231 or (Principles of Math 12 with a C or Pre-Calculus 12 with a C or equivalent) OR currently active in the:PDD Supply Chain Management or PBD International Supply Chain Management or PDD Accounting Studies orPDD Accounting orPBD Accounting orPDD Data Analytics orPBD Computer and Information Systems',
        prerequisites: [
          ['PDDATA'],
          ['PBDCIS'],
          ['PDSCMGT'],
          ['PBDISCM'],
          ['PDACCS'],
          ['PDACCT'],
        ],
        title: 'Business Statistics',
        credit: '3.00',
      },
      {
        url: '/course/busn-3431',
        course_code: 'BUSN 3431',
        prerequisitesStr: '(BUSN 2429 or MATH 1160) with a minimum grade of C',
        prerequisites: [['BUSN 2429'], ['MATH 1160']],
        title: 'Business Statistics II',
        credit: '3.00',
      },
      {
        url: '/course/csis-3300',
        course_code: 'CSIS 3300',
        prerequisitesStr: 'Min grade C in CSIS 2300 ',
        prerequisites: [['CSIS 2300']],
        title: 'Database II',
        credit: '3.00',
      },
      {
        url: '/course/csis-3360',
        course_code: 'CSIS 3360',
        prerequisitesStr:
          'min grade of C in CSIS 2200 AND (BUSN 2429 or MATH 1160)\n(Note: CSIS 2300 is recommended)\nStudents are expected to be comfortable using MS Excel. For those needing upgrading, CSIS 1190 is recommended.',
        prerequisites: [
          ['CSIS 2200', 'BUSN 2429'],
          ['CSIS 2200', 'MATH 1160'],
        ],
        title: 'Fundamentals of Data Analytics',
        credit: '3.00',
      },
      {
        url: '/course/csis-3860',
        course_code: 'CSIS 3860',
        prerequisitesStr:
          'Principles of Math 12 with a C or Pre-Calculus 12 with a C or equivalent \nOR currently active in:\nPDD Data Analytics\nPBD Computer and Information Systems',
        prerequisites: [['PDDATA'], ['PBDCIS']],
        title: 'Data Visualization',
        credit: '3.00',
      },
      {
        url: '/course/csis-4260',
        course_code: 'CSIS 4260',
        prerequisitesStr: 'min grade C in (CSIS 3300 OR CSIS 3360)',
        prerequisites: [['CSIS 3300'], ['CSIS 3360']],
        title: 'Special Topics in Data Analytics',
        credit: '3.00',
      },
      {
        url: '/course/csis-4495',
        course_code: 'CSIS 4495',
        prerequisitesStr:
          'A minimum C grade in the following courses:\nCSIS 2300 and CSIS 3275\nand (CSIS 4175 or 2 of (CSIS 3300, CSIS 3360, CSIS 3860)).\n \nIt is recommended that a student should have obtained 45 credits towards a CSIS credential such as the PBD-CIS before attempting this course.',
        prerequisites: [
          ['CSIS 2300', 'CSIS 3275', 'CSIS 4175'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3300', 'CSIS 3360'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3360', 'CSIS 3860'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3860', 'CSIS 3300'],
        ],
        title: 'Applied Research Project',
        credit: '3.00',
      },
      [
        [
          {
            url: '/course/busn-3380',
            course_code: 'BUSN 3380',
            prerequisitesStr:
              'BUSN 1210  and  (BUSN 2429, or MATH 1160, or B+ in MATH 12), Instructor Permission OR currently active in the:PDD Data Analytics AND BUSN 2429 or PDD Hospitality Management or PBD Computer and Information Systems AND BUSN 2429.',
            prerequisites: [
              ['BUSN 1210', 'BUSN 2429'],
              ['BUSN 1210', 'MATH 1160'],
              ['BUSN 1210', 'MATH 12'],
              ['PDDATA', 'BUSN 2429'],
              ['PDDHOSP'],
              ['PBDCIS', 'BUSN 2429'],
            ],
            title: 'Operations Management',
            credit: '3.00',
          },
          {
            url: '/course/busn-3388',
            course_code: 'BUSN 3388',
            prerequisitesStr:
              'Minimum grade of C in [(BUSN 2429 or MATH 1160) and BUSN 3380], permission of the instructor, OR currently active in the:PDD Supply Chain Management AND a minimum grade of C in BUSN 3380, orPBD Computer and Information Systems AND a minimum grade of C in BUSN 3380.\n ',
            prerequisites: [
              ['BUSN 3380', 'BUSN 2429'],
              ['BUSN 3380', 'MATH 1160'],
              ['BUSN 3380', 'PBDCIS'],
            ],
            title: 'Supply Chain Planning',
            credit: '3.00',
          },
        ],
        [
          {
            url: '/course/csis-3280',
            course_code: 'CSIS 3280',
            prerequisitesStr: 'Min grade C in CSIS 1280',
            prerequisites: [['CSIS 1280']],
            title: 'Web Based Scripting',
            credit: '3.00',
          },
          {
            url: '/course/csis-3380',
            course_code: 'CSIS 3380',
            prerequisitesStr: 'CSIS 1280 with grade C or better',
            prerequisites: [['CSIS 1280']],
            title: 'Advanced Web Programming with JavaScript\u00a0and AJAX',
            credit: '3.00',
          },
        ],
        [
          {
            url: '/course/mark-3235',
            course_code: 'MARK 3235',
            title: 'E-Marketing',
            credit: '3.00',
            prerequisites: [['MARK 1120']],
            prerequisitesStr: 'MARK 1120  ',
          },
          {
            url: '/course/mark-1120',
            course_code: 'MARK 1120',
            prerequisitesStr:
              'Academic Math 11 with a grade of \u201cC\u201d or better or an approved equivalent\nOR currently active in one of the following:\nPost-Degree Diploma in MarketingPost-Degree Diploma in SalesPost-Degree Diploma in Project ManagementPost-Degree Diploma in International Business ManagementPost-Baccalaureate Diploma in International Supply Chain ManagementPost-Degree Diploma in Data AnalyticsPost-Baccalaureate Diploma in Computer and Information SystemsPost-Degree Diploma in Hospitality MarketingPost Baccalaureate Diploma in Hospitality Services Management',
            prerequisites: [
              ['PDMARK'],
              ['PDSALE'],
              ['PDPMGMT'],
              ['PDIBM'],
              ['PBDISCM'],
              ['PDDATA'],
              ['PBDCIS'],
              ['PDHOMK'],
              ['PBHSMT'],
            ],
            title: 'Introductory Marketing',
            credit: '3.00',
          },
        ],
        [
          {
            url: '/course/mark-4360',
            course_code: 'CSIS 4360',
            title: 'Customer Relationship Management',
            credit: '3.00',
            prerequisites: [
              ['MARK 1120', 'CMNS 1115'],
              ['MARK 1120', 'PDMARK'],
              ['MARK 1120', 'PDSALE'],
              ['MARK 1120', 'PDHOMK'],
              ['MARK 1120', 'PBHSMT'],
            ],
            prerequisitesStr:
              'MARK 1120 and (CMNS 1115 or any English UT course)ORMARK 1120 AND currently active in one of the following:Post-Degree Diploma in Marketing orPost-Degree Diploma in Sales orPost-Degree Diploma in Hospitality Marketing orPost Baccalaureate Diploma in Hospitality Services Management',
          },
          {
            url: '/course/mark-1120',
            course_code: 'MARK 1120',
            prerequisitesStr:
              'Academic Math 11 with a grade of \u201cC\u201d or better or an approved equivalent\nOR currently active in one of the following:\nPost-Degree Diploma in MarketingPost-Degree Diploma in SalesPost-Degree Diploma in Project ManagementPost-Degree Diploma in International Business ManagementPost-Baccalaureate Diploma in International Supply Chain ManagementPost-Degree Diploma in Data AnalyticsPost-Baccalaureate Diploma in Computer and Information SystemsPost-Degree Diploma in Hospitality MarketingPost Baccalaureate Diploma in Hospitality Services Management',
            prerequisites: [
              ['PDMARK'],
              ['PDSALE'],
              ['PDPMGMT'],
              ['PDIBM'],
              ['PBDISCM'],
              ['PDDATA'],
              ['PBDCIS'],
              ['PDHOMK'],
              ['PBHSMT'],
            ],
            title: 'Introductory Marketing',
            credit: '3.00',
          },
        ],
      ],
    ],
    security: [
      {
        url: '/course/csis-3270',
        course_code: 'CSIS 3270',
        prerequisitesStr: 'Min grade C in CSIS 2270',
        prerequisites: [['CSIS 2270']],
        title: 'Advance Networking',
        credit: '3.00',
      },
      {
        url: '/course/csis-4270',
        course_code: 'CSIS 4270',
        prerequisitesStr: 'Min grade C in CSIS 3155',
        prerequisites: [['CSIS 3155']],
        title: 'Cloud Infrastructure',
        credit: '3.00',
      },
      {
        url: '/course/csis-3560',
        course_code: 'CSIS 3560',
        prerequisitesStr: ' Min grade C in CSIS 2260 and 2270',
        prerequisites: [['CSIS 2260', 'CSIS 2270']],
        title: 'Scripting for CyberSecurity',
        credit: '3.00',
      },
      {
        url: '/course/csis-4440',
        course_code: 'CSIS 4440',
        prerequisitesStr: 'Min grade of C in CSIS 3175, 3160, and 3560',
        prerequisites: [['CSIS 3175', 'CSIS 3160', 'CSIS 3560']],
        title: 'Mobile CyberSecurity',
        credit: '3.00',
      },
      {
        url: '/course/csis-4450',
        course_code: 'CSIS 4450',
        prerequisitesStr:
          'A grade of C or better in CSIS 3160 , CSIS 2300, AND CSIS 3560',
        prerequisites: [['CSIS 3160', 'CSIS 2300', 'CSIS 3560']],
        title: 'Operating System & Multimedia CyberSecurity',
        credit: '3.00',
      },
      {
        url: '/course/csis-4460',
        course_code: 'CSIS 4460',
        prerequisitesStr: 'Min grade C in CSIS 4270 and 3560',
        prerequisites: [['CSIS 4270', 'CSIS 3560']],
        title: 'Cloud CyberSecurity',
        credit: '3.00',
      },
      {
        url: '/course/csis-4470',
        course_code: 'CSIS 4470',
        prerequisitesStr:
          'Minimum grade of C in CSIS 3560, CSIS 3270 and CSIS 3160\n ',
        prerequisites: [['CSIS 3560', 'CSIS 3270', 'CSIS 3160']],
        title: 'Network CyberSecurity',
        credit: '3.00',
      },
      {
        url: '/course/csis-4480',
        course_code: 'CSIS 4480',
        prerequisitesStr: 'Min grade C in any 2 of (CSIS 4440, 4450, 4470)',
        prerequisites: [
          ['CSIS 4440', 'CSIS 4450'],
          ['CSIS 4470', 'CSIS 4450'],
          ['CSIS 4440', 'CSIS 4470'],
        ],
        title: 'Vulnerabilities and Exploits',
        credit: '3.00',
      },
      {
        url: '/course/csis-4490',
        course_code: 'CSIS 4490',
        prerequisitesStr:
          'Min grade C in any 2 of (CSIS 4440, 4450, 4460, 4470)',
        prerequisites: [
          ['CSIS 4440', 'CSIS 4450'],
          ['CSIS 4450', 'CSIS 4460'],
          ['CSIS 4460', 'CSIS 4470'],
          ['CSIS 4470', 'CSIS 4440'],
        ],
        title: 'Special Topics on CyberSecurity',
        credit: '3.00',
      },
      {
        url: '/course/csis-4495',
        course_code: 'CSIS 4495',
        prerequisitesStr:
          'A minimum C grade in the following courses:\nCSIS 2300 and CSIS 3275\nand (CSIS 4175 or 2 of (CSIS 3300, CSIS 3360, CSIS 3860)).\n \nIt is recommended that a student should have obtained 45 credits towards a CSIS credential such as the PBD-CIS before attempting this course.',
        prerequisites: [
          ['CSIS 2300', 'CSIS 3275', 'CSIS 4175'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3300', 'CSIS 3360'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3360', 'CSIS 3860'],
          ['CSIS 2300', 'CSIS 3275', 'CSIS 3860', 'CSIS 3300'],
        ],
        title: 'Applied Research',
        credit: '3.00',
      },
    ],
  },
};
