# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: standard
# provisioner: kubernetes.io/aws-ebs
# # parameters: # this is used as default for AWS
# #   type: gp2
# #   iopsPerGB: "10"
# #   fsType: ext4
# reclaimPolicy: Retain
# allowVolumeExpansion: true
# # mountOptions:
#   # - debug
# volumeBindingMode: WaitForFirstConsumer

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
