apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
  namespace: course-planning
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/vnbao/Documents/temps/course-planning"
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc
  namespace: course-planning
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi